version: '3'

services:
    activity-service:
        container_name: activity-service
        build: .
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./src/:/code/
        env_file:
            - '.env'