apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-service
  namespace: default
  labels:
      app: activity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activity-service
  template:
    metadata:
      labels:
        app: activity-service
    spec:
      containers:
      - name: activity-service
        image: xxxx # imagen
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: activity-service/monitoring/health-check/
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 43200
        readinessProbe:
          httpGet:
            path: activity-service/monitoring/health-check/
            port: 8000
        envFrom:
        - secretRef:
            name: activity-service-secret
        command:  ["python", "src/manage.py", "runserver", "0.0.0.0:8000"]
        ports:
          - name: tcp
            containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
