apiVersion: v1
kind: Service
metadata:
  name: activity-service
  namespace: default
  labels:
    app: activity-service
spec:
  type: NodePort
  selector:
    app: activity-service
  ports:
    - port: 8000
      targetPort: 8000
