# Generated by Django 4.0 on 2022-01-27 17:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.UUIDField(db_index=True)),
                ('project', models.UUIDField(db_index=True)),
                ('rule', models.UUIDField(db_index=True)),
                ('payment', models.UUIDField(db_index=True)),
                ('project_name', models.CharField(default=None, max_length=60, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True)),
                ('title', models.CharField(default=None, max_length=200, null=True)),
                ('message', models.CharField(default=None, max_length=300, null=True)),
                ('footer', models.CharField(default=None, max_length=200, null=True)),
                ('rule_name', models.CharField(default=None, max_length=60, null=True)),
                ('rule_icon', models.CharField(default=None, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activities',
                'managed': True,
            },
        ),
    ]
