# Generated by Django 4.0 on 2022-02-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('E', 'Event'), ('S', 'Saving')], default=None, max_length=1, null=True),
        ),
    ]
