# Generated by Django 4.0 on 2022-03-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_alter_activity_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='rule',
            field=models.UUIDField(db_index=True, null=True),
        ),
    ]
